openapi: 3.1.0
info:
  version: 0.0.1
  title: Seek backend
  description: Endpoints for the seek secret service
servers:
  - url: https://api.alexpts.dev/v1/seec
paths:
  /secret:
    post:
      tags:
        - Seec
      summary: Save an encrypted secret to the DB
      operationId: saveSecret
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSecretRequest'
      responses:
        200:
          description: Saved secret to the DB
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewSecretResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'
  /secret/{secretId}:
    get:
      tags:
        - Seec
      summary: Get a secret from the DB
      operationId: getSecret
      parameters:
        - name: secretId
          in: path
          required: true
          description: The id of the secret to retrieve
          schema:
            type: string
      responses:
        200:
          description: Retrieved secret from the DB
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSecretResponse'
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefaultErrorResponse'

components:
  schemas:
    NewSecretRequest:
      type: object
      required:
        - secret
        - iv
        - auto_expire_at
      properties:
        secret:
          type: string
          example: "FA45CUZ2gLCB2U5OPtQ"
        iv:
          type: string
          example: "FrQZAYpqAtUtp-OO"
        auto_expire_at:
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
    NewSecretResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          example: "If3qs4o8qHcyJ0L1tliSzuh48"
    GetSecretResponse:
      type: object
      required:
        - secret
        - iv
      properties:
        secret:
          type: string
          example: "FA45CUZ2gLCB2U5OPtQ"
        iv:
          type: string
          example: "FrQZAYpqAtUtp-OO"
        auto_expire:
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
    DefaultErrorResponse:
      type: object
      required:
        - http_code
        - error_message
        - error_code
      properties:
        http_code:
          type: integer
          format: int32
          minimum: 400
          maximum: 599
        error_message:
          type: string
          example: "Could not find secret with id xyz"
        error_code:
          type: integer
          format: int32
          example: 1001
