server:
  port: 9911

logging:
  level:
    liquibase: INFO
    org.springframework.web: DEBUG

spring.datasource:
  url: jdbc:postgresql://localhost:5432/seec
  username: seec
  password: seec-pw
  hikari:
    connection-timeout: 5000
    spring:
